package com.china.reader.imagereader;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.china.reader.imagereader.bean.ImagePage;
import com.china.reader.imagereader.bean.User;
import com.china.reader.imagereader.bean.ImageBean;

import com.china.reader.imagereader.ImagePageDao;
import com.china.reader.imagereader.UserDao;
import com.china.reader.imagereader.ImageBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imagePageDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig imageBeanDaoConfig;

    private final ImagePageDao imagePageDao;
    private final UserDao userDao;
    private final ImageBeanDao imageBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imagePageDaoConfig = daoConfigMap.get(ImagePageDao.class).clone();
        imagePageDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        imageBeanDaoConfig = daoConfigMap.get(ImageBeanDao.class).clone();
        imageBeanDaoConfig.initIdentityScope(type);

        imagePageDao = new ImagePageDao(imagePageDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        imageBeanDao = new ImageBeanDao(imageBeanDaoConfig, this);

        registerDao(ImagePage.class, imagePageDao);
        registerDao(User.class, userDao);
        registerDao(ImageBean.class, imageBeanDao);
    }
    
    public void clear() {
        imagePageDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        imageBeanDaoConfig.clearIdentityScope();
    }

    public ImagePageDao getImagePageDao() {
        return imagePageDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ImageBeanDao getImageBeanDao() {
        return imageBeanDao;
    }

}
