package com.china.reader.imagereader;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.china.reader.imagereader.bean.ImagePage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IMAGE_PAGE".
*/
public class ImagePageDao extends AbstractDao<ImagePage, Long> {

    public static final String TABLENAME = "IMAGE_PAGE";

    /**
     * Properties of entity ImagePage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property WebIndex = new Property(1, int.class, "webIndex", false, "WEB_INDEX");
        public final static Property PageIndex = new Property(2, int.class, "pageIndex", false, "PAGE_INDEX");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property AlbumImage = new Property(4, String.class, "albumImage", false, "ALBUM_IMAGE");
        public final static Property IsViewed = new Property(5, boolean.class, "isViewed", false, "IS_VIEWED");
        public final static Property IsFavorite = new Property(6, boolean.class, "isFavorite", false, "IS_FAVORITE");
    }


    public ImagePageDao(DaoConfig config) {
        super(config);
    }
    
    public ImagePageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IMAGE_PAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"WEB_INDEX\" INTEGER NOT NULL ," + // 1: webIndex
                "\"PAGE_INDEX\" INTEGER NOT NULL ," + // 2: pageIndex
                "\"TITLE\" TEXT UNIQUE ," + // 3: title
                "\"ALBUM_IMAGE\" TEXT," + // 4: albumImage
                "\"IS_VIEWED\" INTEGER NOT NULL ," + // 5: isViewed
                "\"IS_FAVORITE\" INTEGER NOT NULL );"); // 6: isFavorite
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IMAGE_PAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ImagePage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getWebIndex());
        stmt.bindLong(3, entity.getPageIndex());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        String albumImage = entity.getAlbumImage();
        if (albumImage != null) {
            stmt.bindString(5, albumImage);
        }
        stmt.bindLong(6, entity.getIsViewed() ? 1L: 0L);
        stmt.bindLong(7, entity.getIsFavorite() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ImagePage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getWebIndex());
        stmt.bindLong(3, entity.getPageIndex());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        String albumImage = entity.getAlbumImage();
        if (albumImage != null) {
            stmt.bindString(5, albumImage);
        }
        stmt.bindLong(6, entity.getIsViewed() ? 1L: 0L);
        stmt.bindLong(7, entity.getIsFavorite() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ImagePage readEntity(Cursor cursor, int offset) {
        ImagePage entity = new ImagePage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // webIndex
            cursor.getInt(offset + 2), // pageIndex
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // title
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // albumImage
            cursor.getShort(offset + 5) != 0, // isViewed
            cursor.getShort(offset + 6) != 0 // isFavorite
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ImagePage entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setWebIndex(cursor.getInt(offset + 1));
        entity.setPageIndex(cursor.getInt(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAlbumImage(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIsViewed(cursor.getShort(offset + 5) != 0);
        entity.setIsFavorite(cursor.getShort(offset + 6) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ImagePage entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ImagePage entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ImagePage entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
