package com.china.reader.imagereader;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.china.reader.imagereader.bean.ImageBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IMAGE_BEAN".
*/
public class ImageBeanDao extends AbstractDao<ImageBean, Long> {

    public static final String TABLENAME = "IMAGE_BEAN";

    /**
     * Properties of entity ImageBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property WebIndex = new Property(1, int.class, "webIndex", false, "WEB_INDEX");
        public final static Property PageIndex = new Property(2, int.class, "pageIndex", false, "PAGE_INDEX");
        public final static Property ImageUrl = new Property(3, String.class, "imageUrl", false, "IMAGE_URL");
        public final static Property Width = new Property(4, int.class, "width", false, "WIDTH");
        public final static Property Height = new Property(5, int.class, "height", false, "HEIGHT");
        public final static Property IsFavorite = new Property(6, boolean.class, "isFavorite", false, "IS_FAVORITE");
    }


    public ImageBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ImageBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IMAGE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"WEB_INDEX\" INTEGER NOT NULL ," + // 1: webIndex
                "\"PAGE_INDEX\" INTEGER NOT NULL ," + // 2: pageIndex
                "\"IMAGE_URL\" TEXT UNIQUE ," + // 3: imageUrl
                "\"WIDTH\" INTEGER NOT NULL ," + // 4: width
                "\"HEIGHT\" INTEGER NOT NULL ," + // 5: height
                "\"IS_FAVORITE\" INTEGER NOT NULL );"); // 6: isFavorite
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IMAGE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ImageBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getWebIndex());
        stmt.bindLong(3, entity.getPageIndex());
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(4, imageUrl);
        }
        stmt.bindLong(5, entity.getWidth());
        stmt.bindLong(6, entity.getHeight());
        stmt.bindLong(7, entity.getIsFavorite() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ImageBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getWebIndex());
        stmt.bindLong(3, entity.getPageIndex());
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(4, imageUrl);
        }
        stmt.bindLong(5, entity.getWidth());
        stmt.bindLong(6, entity.getHeight());
        stmt.bindLong(7, entity.getIsFavorite() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ImageBean readEntity(Cursor cursor, int offset) {
        ImageBean entity = new ImageBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // webIndex
            cursor.getInt(offset + 2), // pageIndex
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // imageUrl
            cursor.getInt(offset + 4), // width
            cursor.getInt(offset + 5), // height
            cursor.getShort(offset + 6) != 0 // isFavorite
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ImageBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setWebIndex(cursor.getInt(offset + 1));
        entity.setPageIndex(cursor.getInt(offset + 2));
        entity.setImageUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setWidth(cursor.getInt(offset + 4));
        entity.setHeight(cursor.getInt(offset + 5));
        entity.setIsFavorite(cursor.getShort(offset + 6) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ImageBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ImageBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ImageBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
