name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        sed -i "1s/123/$PASSWORD/" keystore.properties
        sed -i "2s/123/$PASSWORD/" keystore.properties
        ./gradlew assembleRelease
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: app/build/outputs/apk/release/app-release.apk

